### ISSUE TITLE
Research audio annotation libraries

### ISSUE THREAD

**Issue by mgogoulos** [eellak/gsoc2021-audio-annotation-tool#10]
https://wavesurfer-js.org/ looks very good, and most projects in this area seem to utilize it. However there might be alternatives that worth to be found? Also if wavesurfer is going to be used, then an exploration on which of the examples it provides suits for the project has to be performed

**Comment by IoannisSina** [comment]
I found this open source tool https://github.com/bbc/waveform-data.js/ for audio visualization but without the annotation feature. I think the best choice is https://wavesurfer-js.org/ which is easy to use and provides everything we need. What do you think?

**Comment by mgogoulos** [comment]
https://github.com/bbc/peaks.js is another interesting project. 

Any of this is fine, with wavesurfer-js looking more stable probably.

**Comment by mgogoulos** [comment]
if a library already has annotation functionality you should do a quick demo on how to setup it, provide your labels and retrieve the values of annotation, also how they can be displayed (eg when you load an existing annotation). Then choose whatever looks better.

**Comment by IoannisSina** [comment]
I'm checking https://wavesurfer-js.org/ but is seems like you cannot play audio without the waveform. Maybe another tool should be used for the project page where the user will be able to hear the audio without the waveform. Do you know if https://wavesurfer-js.org/ can be used without the waveform?

**Comment by mgogoulos** [comment]
For something as simple as showing the start/stop for audio, you should use the vanilla html5 elements - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

**Comment by IoannisSina** [comment]
I used https://wavesurfer-js.org/  for the annotation  page as it offers everything we need.
